config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :searches
  resources :users
  resources :cars
  root 'cars#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ActiveRecord::Base
    
  belongs_to :user
  has_many :car_images, :dependent => :destroy
  accepts_nested_attributes_for :car_images, :reject_if => :all_blank, :allow_destroy => true

  def main_image
    car_images.first.image
  end

  def all_image
    car_images.all
  end

  def self.search(search)
    where("make LIKE ? OR model LIKE ? OR color_type LIKE ? OR year LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
  end

  def self.advanced_search(make,model,color_type,start_year,end_year)
    where("make LIKE ? AND model LIKE ? AND color_type LIKE ? AND (year BETWEEN ? AND ?)", "%#{make}%", "%#{model}%", "%#{color_type}%", start_year, end_year) 
  end
end

app/models/car_image.rb
class CarImage < ApplicationRecord
	
	belongs_to :car

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/search.rb
class Search < ApplicationRecord

  belongs_to :car

  def self.search_cars
		cars = Car.all
	  cars = cars.where(make: search.make) if search.make.present?
	  cars = cars.where(model: model) if model.present?
	  cars = cars.where(color_type: color) if color.present?
	 	cars = cars.where(["year BETWEEN ? AND ?", start_year, end_year]) if start_year && end_year
    return cars
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # users.password_hash in the database is a :string
  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy] 
  # GET /cars
  # GET /cars.json
  def index     
     @cars = Car.all
    if params[:search]
      @cars = Car.search(params[:search]).order(:make)
    else
      @cars = Car.order(:make)
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    @car.user_id = current_user.id
          
    respond_to do |format|
      if @car.save

        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update

    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:make, :model, :color_type, :year, :description, :price, :condition, car_images_attributes: [:id, :image, :_destroy])
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController	
  def index
    @cars = Car.advanced_search(params[:make],params[:model],params[:color],params[:start_year],params[:end_year])
	end
  
	def new
	end
	
	private
    def search_params
      params.require(:search).permit(:make, :model, :color, :start_year, :end_year)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :verify_authenticity_token

  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password]) && user.name == params[:name]
  		session[:user_id] = user.id
  		redirect_to root_path
  	else 
  		redirect_to root_path, notice: 'Your credintials do not fit our records, Please sign up or try again'
  	end	
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path, notice: 'User was successfully created.' } 
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_advanced_search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>Advanced search</h1>
    </div> 
  </div>
  <div class="row">
    <div class="col-md-6"> 
      <%= bootstrap_form_tag method: :get do %>
        <%= text_field_tag :make %>
        <%= text_field_tag :model%>
        <%= text_field_tag :color%>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-3">        
      <%= select_tag(:year, 1940..2017, as: :start_year) %>
      <%= select_tag(:year, 1940..2017, as: :end_year) %>
      <%= submit_tag "search", class: "btn btn-primary", style: "padding: 5px 70px; font-size: 120%" %>
      <%end%>        
    </div>  
  </div>
</div>

app/views/cars/_detail_card.html.erb
<div class="panel" style="border: 0">
  <div class="panel-heading text-center shadow" style="background-color: #204060">
    <div class="row">
      <div class="col-md-12">
        <h2 style="color: white; font-weight: bold">
          <%= @car.year %>
          <%= @car.make %>
          <%= @car.model %>
          <%= @car.color_type %>
        </h2>
      </div>  
    </div>
  </div>
	<div class="container shadow" style="background-color: #E8E8E8">
		<div class="row">
			<div class="col-md 12">	
			  <h4>Description: <span style="color: grey"><%= @car.description %></span></h4>
      </div>
		</div>
		<hr class="small">
		<div class="row">
      <div class="col-md 12">
			  <h4>Price: $<span style="color: grey"><%= @car.price %></span></h4>
      </div>
		</div>
		<hr class="small">
		<div class="row">
      <div class="col-md 12">
			  <h4>Car Condition: <span style="color: grey"><%= @car.condition %></span></h4>
      </div>  
		</div>
	</div>	
</div>

app/views/cars/_form.html.erb
<%= bootstrap_nested_form_for(@car) do |f| %>
<div class="form-group">
  <% if @car.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>
    <ul>
      <% @car.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>   
  <%= f.text_field :make, class: "form-control", placeholder: "Enter car make" %>
  <%= f.text_field :model, class: "form-control", placeholder: "Enter car model" %>
  <%= f.select(:color_type, options_for_select([['Red', 'Red'], ['Blue', 'Blue'], ['Black', 'Black'], ['White', 'White'], ['Green', 'Green'], ['Yellow', 'Yellow'], ['Grey', 'Grey'], ['Silver', 'Silver']])) %>
  <%= f.text_field :year, class: "form-control", placeholder: "Enter Year" %>
  <%= f.text_field :description, class: "form-control", placeholder: "Enter Description" %>
  <%= f.text_field :price, class: "form-control", placeholder: "Enter Price" %>
  <%= f.select(:condition, options_for_select([['Excellent', 'Excellent'], ['Good', 'Good'], ['Fair', 'Fair'], ['Poor', 'Poor']])) %>
  <%= f.fields_for :car_images do |image_form| %>
  <%= image_form.file_field :image %>
  <%= image_form.link_to_remove "Remove this Image" %>
  <% end %>
  <p><%= f.link_to_add "Add an Image", :car_images %></p>

  <div class="row">
    <div class="col-md-1">
      <input class="btn btn-primary" type="submit" value="Submit">
    </div>
<% end %>

app/views/cars/_header.html.erb
  
<!-- navbar -->

<nav class="navbar navbar-inverse navbar-fixed-top row">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    
    <div id="navbar" class="collapse navbar-collapse">
      <a class="navbar-brand" href="<%= root_path %>">CarList</a>
      <ul class="nav navbar-nav" style="display: inline">
        <li><a class="navbar-brand" href="<%= root_path %>">Cars</a></li>
        <% if current_user %>
        <li><a class="navbar-brand" href="<%= new_car_path %>">Add New Car</a></li>
        <% end %>
        <!--  generate search query -->

        <li><form class="navbar-form">
          <div class="form-group col-md-12">
            <%= form_tag cars_path ,method: 'get' do %>
            <%= text_field_tag :search , params[:search], placeholder: "Search Cars", class: "form-control" %>
            <%= submit_tag "Search Cars", :name => nil, class:"btn btn-success"%>
            <% end %>
          </div>
        </form></li>
      </ul>

      <!--  user authentication -->

      <% if user_signed_in? %>


      <form class="navbar-form">
        <p style="color: white">Hello <%= current_user.name %> : <%= link_to "Sign_out", destroy_user_session_path, :method => 'delete', class: "btn btn-success" %></p>
      </form>

      <% else %>

      <div class="navbar-form navbar-right" style="color: white">
        <div>
          <a class="btn btn-success" href="<%= new_user_session_path %>" role="button">Please Sign In </a>
          OR 
          <a class="btn btn-success" href="<%= new_user_registration_path %>" role="button"> Sign Up</a>
        </div>  
      </div>
      <% end %>
    </div><!--/.navbar-collapse --> 
  </div><!-- /.container-fluid -->  
</nav>

app/views/cars/edit.html.erb
<div class="container" style="margin-top: 40px; margin-bottom: 140px">
	<div class="col-10">
		<p style="font-size: 200%">Edit Car</p> 

		<%= render 'form' %>
		
		<div class="col-md-1">
			<a class="btn btn-primary" href="<%= root_path %>" role="button">Back</a>
		</div>
		

		<div class="col-md-1">
			<%= link_to 'Delete', @car, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
		</div>
	</div>
</div>   	
</div> 

app/views/cars/index.html.erb
<div class="container">
  <div align="center">      
    <h1 style="font-size: 300%">Our Cars</h1>
  </div>  
  <!-- condition on adding cars --> 
  <div class="row">  
    <% if current_user %>
    <div class="col-md-12" align="center">
      <p class="text-center"><a class="btn btn-primary" href="<%= new_car_path %>" role="button" style="padding: 6px 70px; font-size: 120%" >Add New Car</a></p>
    </div>
    <% else %>
    <div class="col-md-12"> 
      <h4 style="color: red" align="center">Please sign in before trying to add\edit cars!</h4>
    </div>
    <% end %>  
  </div>
  <!--  generating car grid --> 
  <div class="row">
    <% @cars.each do |car| %>
    <div class="col-md-4">
    <div class="panel panel-primary">
      <a style="text-decoration: none" href="<%= car_path(car) %>">
        <div class="panel-body" align="center"><%= image_tag car.main_image.url, class: "img-responsive thumbnail", style: "height: 200px; width: 300px" %>
        </div>  
        <div class="panel-footer text-center">  
          <h4><%= car.year %>
            <%= car.make %>
            <%= car.model %></h4>
            <p> 
              <h4>Click For More Details</h4>
            </p>
          </div>
        </a>
      </div>
      </div>  
      <% end %>
    </div>
    <!-- create advanced search query -->
    <div align="center">
      <%= link_to "Advanced Search", new_search_path, class: "btn btn-secondary active"%>
    </div>
  </div> 

app/views/cars/new.html.erb
<div class="container" style="margin-top: 40px; margin-bottom: 140px">
  <div class="row">
    <div class="col-md-6">
      <p style="font-size: 200%">New Car</p>
        <%= render 'form' %>
  	    <div class="col-md-4">
  	     	<a class="btn btn-primary" href="<%= root_path %>" role="button">Back</a>
  	    </div>
      </div>	
  </div>
</div>    

app/views/cars/show.html.erb
<div class="container" style="margin-top: 4%">
  <div class="row tag">
    <% if @car.car_images.count == 1 %>
    <div class="col-md-12">
      <div class="col-md-6">
        <%= render 'detail_card' %>
      </div>  
      <div class="col-md-6" align="center" style="margin-bottom: 50px"><%= image_tag @car.main_image.url(:medium), class: "img-responsive", height: "300px", width: "400px" %>
      </div>   
    <% else %>  
      <!--  Image carousel -->
      <div class="col-md-12">
        <div class="col-md-6">
          <%= render 'detail_card' %>
        </div>
        <div class="col-md-6">
          <div id="myCarousel" role = "navigation" class="carousel slide carousel-fade" data-ride="carousel" style="max-height: 200px">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <% @car.car_images.each_with_index do |car_image, index| %>
                <% if index == 0 %>
                  <div class="item active" align="center"><%= image_tag car_image.image.url(:medium), class: "img-responsive", style: "max-height: 200px" %>
                  </div>  
                <% else %>
                  <div class="item" align="center"><%= image_tag car_image.image.url(:medium), class: "img-responsive", style: "min-height: 200px" %>
                  </div>  
                <% end %>     
              <% end %>
            </div>
            <!-- Carousel Controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div><br><br>  
        </div>  
      <% end %>
          <!-- edit button if signed in  -->
          <div align="center">   
            <% if current_user && @car.user_id == current_user.id %>
            <a class="btn btn-primary" href="<%= edit_car_path(@car) %>" role="button" style="padding: 6px 70px; font-size: 120%">Edit</a>
            <a class="btn btn-primary" href="<%= root_path %>" role="button" style="padding: 6px 70px; font-size: 120%">Back</a>
            <% else %>
            <% if current_user %>
            <h4 style="color: #A52A2A; font-weight: bold">You can only edit and delete cars you created.</h4><br>
            <a class="btn btn-primary" href="<%= root_path %>" role="button" style="padding: 6px 70px; font-size: 120%">Back</a>
            <% else %>
            <h4 style="color: #A52A2A; font-weight: bold">Please sign in before trying to add\edit cars!</h4><br>
            <a class="btn btn-primary" href="<%= root_path %>" role="button" style="padding: 6px 70px; font-size: 120%">Back</a>
            <% end %>
            <% end %>
          </div> 
        </div> 
      </div>
    </div> 
  </div> 

app/views/layouts/_footer.html.erb
<footer class="padl footer font navbar-fixed-bottom" style="background-color: #B0C4DE; padding-top: 20px; padding-bottom: 20px">
  <div class="container">
    <div class="row">
      <div class="col-md-7 col-xs-12 col-sm-12">
        <div class="row">
          <h4 style="padding-left:10px"><%= link_to "ABOUT US", style: "color: #005ce6" %>
          </h4>
          <h4 style="padding-left:10px"><%= link_to "PRESS", style: "color: #005ce6" %>
          </h4>
          <h4 style="padding-left:10px"><%= link_to "PRIVACY", style: "color: #005ce6" %>
          </h4>
          <h4 style="padding-left:10px"><%= link_to "TERMS", style: "color: #005ce6" %>
          </h4>
        </div>  
      </div>
      <div class="col-md-3 col-md-push-1 col-xs-12 col-sm-12">
        <h4 class="grey"><%= "\u00A9" %><%= link_to "CarList 2017", style: "color: #606060" %>
        </h4>                                     
      </div>  
      <div class="col-md-2 col-xs-12 col-sm-12">
        <div class="row">
          <div class="sm" style="padding-left:15px">
            <a href="https://www.facebook.com/wearecatchapp/"><%= image_tag "fb_icon.png", class: "img-responsive" %></a>
            <a href="#" ><%= image_tag "LI-icon.png", class: "img-responsive" %></a>
            <a href="#" ><%= image_tag "twitter-logo-4.png", class: "img-responsive" %></a>
            <a href="https://www.instagram.com/wearecatchapp/" ><%= image_tag "new-instagram-icon-2.png", class: "img-responsive" %></a>
          </div>
        </div>
      </div>
    </div> 
  </div>     
</footer>

app/views/layouts/_navbar.html.erb
  
<!-- navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top row">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>   
    <div id="navbar" class="collapse navbar-collapse">
      <a class="navbar-brand" href="<%= root_path %>">CarList</a>
      <ul class="nav navbar-nav" style="display: inline">
        <li><a class="navbar-brand" href="<%= root_path %>">Cars</a></li>
        <% if current_user %>
        <li><a class="navbar-brand" href="<%= new_car_path %>">Add New Car</a></li>
        <% end %>
        <!--  generate search query -->
        <li>
          <div class="col-md-12 navbar-form">
            <%= form_tag cars_path ,method: 'get' do %>
              <%= text_field_tag :search , params[:search], placeholder: "Search Cars", class: "form-control" %>
              <%= submit_tag "Search Cars", :name => nil, class:"btn btn-success"%>
            <% end %>
          </div>
        </li>
      </ul>
      <!--  user authentication -->
      <% if user_signed_in? %>
        <p class="navbar-right" style="color: white; margin-top: 8px">Hello <%= current_user.name %> : <%= link_to "Sign_out", destroy_user_session_path, :method => 'delete', class: "btn btn-success" %></p>
      <% else %>
        <div class="navbar-right" style="color: white; margin-top: 8px">
          <div>
            <a class="btn btn-success" href="<%= new_user_session_path %>" role="button">Please Sign In </a>
            OR 
            <a class="btn btn-success" href="<%= new_user_registration_path %>" role="button"> Sign Up</a>
          </div>  
        </div>
      <% end %>
    </div><!--/.navbar-collapse --> 
  </div><!-- /.container-fluid -->  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>	
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

	<title>CarList</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	<!-- daterangepicker Required Prerequisites -->

	<script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
	<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
	<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/3/css/bootstrap.css" />

	<!-- including daterangepicker -->	

	<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
	<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
	

	<!-- Latest compiled and minified CSS -->

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	
	<!-- for small device layout -->
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">


</head>

<body class="font" style="background-color: #E8E8E8">
	<%= render 'layouts/navbar' %>
	<div style="margin-bottom: 200px">
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/searches/index.html.erb
<div class="container">
	<div class="text-center">
		<h1>Search Results</h1>
	</div>

	<% if !@cars %>
	
	<div class="text-center">
		<h3 class="highlight">No records found!</h3>
	</div>

	<% else %>

	<div align="center">
		<% @cars.each do |c| %>
		<p class="text-center">Make : <%= c.make %></p>
		<p class="text-center">Model : <%= c.model %></p>
		<p class="text-center">Color : <%= c.color %></p>
		<p class="text-center">Year : <%= c.year %></p>
		<p class="thumbnail col-md-4"><%= image_tag c.main_image.url(:medium), height: "80%", width: "80%", class: "img-responsive" %></p>
		<% end %>	
	</div>
	
	<center><div class="col-md-1">
		<a class="btn btn-primary" href="<%= root_path %>" role="button">Back</a>
	</div></center>

	<% end %>

</div>

app/views/searches/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>Advanced search</h1>
    </div> 
  </div>
  <div class="row">
    <div class="col-md-6"> 
      <%= bootstrap_form_tag(url: searches_path, method: :get) do |f| %>
        <%= f.text_field :make, placeholder: "Make" %>
        <%= f.text_field :model, placeholder: "Model" %>
        <%= f.text_field :color, placeholder: "Color" %>
    </div>
    <div class="col-md-6">
    </div>
    <div class="col-md-3">        
        <%= f.select(:start_year, 1940..2017) %>
        <%= f.select(:end_year, 1940..2017) %>
        <%= f.submit "search", class: "btn btn-primary", style: "padding: 5px 70px; font-size: 120%" %>
      <% end %>        
    </div>  
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">

  <div class="form-group row">
    <div class="col-10">
      <p style="font-size: 200%">Users</p>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-1">
      <p style="text-decoration: underline">Name</p>
    </div>
    <div class="col-1">
      <p style="text-decoration: underline">Email</p>
    </div>
  </div> 

  <div class="form-group row">
      <% @users.each do |user| %>
          <div class="col-1"><%= user.name %></div>
          <div class="col-2"><%= user.email %></div>
          
          <div class="col-1">
            <a class="btn btn-primary btn-sm" href="<%= user_path(user) %>" role="button">Show</a> 
          </div>
          
          <div class="col-1">
            <a class="btn btn-primary btn-sm" href="<%= edit_user_path(user) %>" role="button">Edit</a> 
          </div>
          
          <div class="col-1">
            <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm" %>
          </div>
          <div class="col-6"></div>
      <% end %>
  </div>

  <a class="btn btn-primary" href="<%= new_user_path %>" role="button">New User</a> 
 
  <a class="btn btn-primary" href="<%= root_path %>" role="button">Back</a>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>